### ISSUE TITLE
Add support for retreiving EDF file

### ISSUE THREAD

**Issue by joschaschmiedt** [zero-noise-lab/unreal-eyeserver-interface#2]
In order to retreive the recored data via ethernet we need to implement the `StartRecording` and `StopRecording` methods with a filename:
```
[00 0 2 filename] start recording
[00 0 0 filename] stop recording (and copy .edf to the specified file)
```

**Note**: This cannot be developed without a real Eyelink system

**Comment by joschaschmiedt** [comment]
I implemented methods for stopping a recording in commit 59301bce824425ebca49a6ade9702704a6bc5271. @KatharineShapcott , this needs to be tested though with a real EyeLink system.

**Comment by KatharineShapcott** [comment]
It is saving EDF files to the Eyelink computer with the correct names.
