### ISSUE TITLE
Warning when disconnecting

### ISSUE THREAD

**Issue by KatharineShapcott** [zero-noise-lab/unreal-eyeserver-interface#4]
Every time I try to disconnect from the Eyeserver it seems to work but the log gives a warning:
LogTemp: Warning: EyeServer: disconnect may have failed

Full log trace looks like:
LogTemp: Display: EyeServer: starting EyeLinkServer
LogTemp: Display: EyeServer: connecting
LogTemp: Display: EyeServer: starting recording without EDF
LogTemp: Display: EyeServer: stopping recording without EDF
LogTemp: Display: EyeServer: stopping recording without EDF
LogTemp: Display: EyeServer: stopping recording without EDF
LogTemp: Display: EyeServer: stopping recording without EDF
LogTemp: Display: EyeServer: stopping recording without EDF
LogTemp: Display: EyeServer: disconnecting
LogTemp: Warning: EyeServer: disconnect may have failed
LogTemp: Display: EyeServer: stopping EyeLinkServer process

**Comment by KatharineShapcott** [comment]
Just noticed I get the same thing for the DaqServer too....

**Comment by KatharineShapcott** [comment]
It's due to trying to the DisconnectNamedPipe(hPipe) failing, which seems actually not to be necessary when we're only connecting to the client side of the pipe:
https://docs.microsoft.com/en-us/windows/win32/ipc/named-pipe-client 
@joschaschmiedt Can you confirm that it's fine for me to delete this line?

**Comment by joschaschmiedt** [comment]
> It's due to trying to the DisconnectNamedPipe(hPipe) failing, which seems actually not to be necessary when we're only connecting to the client side of the pipe:
> https://docs.microsoft.com/en-us/windows/win32/ipc/named-pipe-client
> @joschaschmiedt Can you confirm that it's fine for me to delete this line?

Yep, you're totally right. `DisconnectNamedPipe` is a function used by the server, not the client. Closing the handle is sufficient.
